from .carga_masiva_page import Carga_masiva_Form
from .menu_superadmon_page import Formato_Menu
from .registro_cliente_page import Registro_clientesForm
from .registro_contratos_page import Registro_contratos_Form