"""añadiendo usuario superadmin

Revision ID: 0ad775097efb
Revises: 4bda24e1bafb
Create Date: 2024-11-28 09:32:00.552149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table

from backend.services.auth_service import AuthService

# revision identifiers, used by Alembic.
revision: str = '0ad775097efb'
down_revision: Union[str, None] = '4bda24e1bafb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

user_table = table(
    'users',
    sa.Column('id', sa.Integer),
    sa.Column('name', sa.String),
    sa.Column('email', sa.String),
    sa.Column('password', sa.String),
    sa.Column('is_superadmin', sa.Boolean),
    sa.Column('tenant_id', sa.Integer),
)

auth_service = AuthService()

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    hased_password = auth_service.get_password('galerastech')
    op.bulk_insert(user_table, [
        {
            "id": 1,
            "name": "admin",
            "email": "admin@galerastech.com",
            "password": hased_password,
            "is_superadmin": True,
            "tenant_id": None,  # Superadmin no necesita estar asociado a un tenant
        }
    ])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM users WHERE email='admin@galerastech.com'")
    # ### end Alembic commands ###
