"""add: super admin

Revision ID: 232d2346208c
Revises: f9baaeea7559
Create Date: 2024-12-04 08:05:17.083691

"""
from socket import fromfd
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table
from backend.security.security import get_password

# revision identifiers, used by Alembic.
revision: str = '232d2346208c'
down_revision: Union[str, None] = 'f9baaeea7559'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

user_table = table(
    'users',
    sa.Column('id', sa.Integer),
    sa.Column('name', sa.String),
    sa.Column('email', sa.String),
    sa.Column('password', sa.String),
    sa.Column('apartment', sa.Integer),
    sa.Column('status', sa.String),
    sa.Column('role', sa.String),
    sa.Column('tenant_id', sa.Integer),
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    hased_password = get_password('galerastech')
    op.bulk_insert(user_table, [
        {
            "id": 1,
            "name": "admin",
            "email": "admin@galerastech.com",
            "password": hased_password,
            "apartment": 0,
            "status": "active",
            "role": "superadmin",
            "tenant_id": None,  # Superadmin no necesita estar asociado a un tenant
        }
    ])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM users WHERE email='admin@galerastech.com'")
    # ### end Alembic commands ###
