"""creacion_de_super_admin

Revision ID: 70a6fa4b0bc1
Revises: 42b964cebb2e
Create Date: 2025-02-25 22:27:34.492799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import table

from backend.services import UserService

# revision identifiers, used by Alembic.
revision: str = '70a6fa4b0bc1'
down_revision: Union[str, None] = '42b964cebb2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


user_table = table(
    'users',
    sa.Column('id', sa.Integer),
    sa.Column('name', sa.String),
    sa.Column('email', sa.String),
    sa.Column('password', sa.String),
    sa.Column('apartment', sa.Integer),
    sa.Column('status', sa.String),
    sa.Column('role', sa.String),
    sa.Column('tenant_id', sa.Integer),
)

auth_service = UserService()

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    hased_password = auth_service.get_password('galerastech')
    op.bulk_insert(user_table, [
        {
            "id": 1,
            "name": "admin",
            "email": "admin@galerastech.com",
            "password": hased_password,
            "apartment": 0,
            "status": "active",
            "role": "superadmin",
            "tenant_id": None,  # Superadmin no necesita estar asociado a un tenant
        }
    ])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM users WHERE email='admin@galerastech.com'")
    # ### end Alembic commands ###
