"""update_users_table

Revision ID: 7f92cf20bba8
Revises: efd4e040b1df
Create Date: 2024-11-14 17:46:32.976840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7f92cf20bba8'
down_revision: Union[str, None] = 'efd4e040b1df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=50), nullable=False))
    op.drop_column('users', 'passwd')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('passwd', mysql.VARCHAR(length=50), nullable=False))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
