"""modificando campo is_superadmin en tabla users

Revision ID: af4bc92997bf
Revises: 0ad775097efb
Create Date: 2024-11-29 15:11:09.622316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af4bc92997bf'
down_revision: Union[str, None] = '0ad775097efb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('is_superadmin', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('is_superadmin', 'users', ['is_superadmin'], unique=True)
    # ### end Alembic commands ###
